// Generated by CoffeeScript 1.4.0
(function() {
  var Calamity;

  Calamity = require("../../../calamity.js");

  describe("EventBus", function() {
    it("should create an empty message", function() {
      var bus, msg;
      bus = new EventBus();
      msg = bus._createMessage();
      return expect(msg instanceof EventMessage).toBe(true);
    });
    it("should create a message with correct address, data, and reply", function() {
      var bus, msg, reply;
      bus = new EventBus();
      reply = function() {};
      msg = bus._createMessage("address", "data", reply);
      expect(msg instanceof EventMessage).toBe(true);
      expect(msg.address).toBe("address");
      expect(msg.data).toBe("data");
      return expect(msg._replyHandler).toBe(reply);
    });
    return it("should create multiple messages", function() {
      var bus, msg1, msg2;
      bus = new EventBus();
      msg1 = bus._createMessage();
      msg2 = bus._createMessage();
      return expect(msg1).toNotBe(msg2);
    });
  });

}).call(this);
